# data
crop_duration: 2.5
crop_stride: 1.25
# model architecture
use_register: True
attn_pooling: False
layer_scale_eps: 0.
bias: False
dropout: 0.05
frozen: False
# training
steps: 10000
batch_size: 128
learning_rate: 1.0e-3
final_learning_rate: 1.0e-5
learning_rate_warmup_steps: 200
weight_decay: 1.0e-2
opt_betas: [0.9, 0.99]
gradient_clip: 0.
checkpoint_interval: 100
early_stopping_patience: 2000