# data
crop_duration: 2.5
crop_stride: 1.25
# model architecture
use_register: True
attn_pooling: True
layer_scale_eps: 0.
bias: False
dropout: 0.
frozen: True
# training
steps: 5000
batch_size: 128
learning_rate: 1.0e-3
final_learning_rate: 1.0e-3
learning_rate_warmup_steps: 0
weight_decay: 1.0e-1
opt_betas: [0.9, 0.999]
gradient_clip: 1.
checkpoint_interval: 100
early_stopping_patience: 5000